import DefaultImage from "../assets/images/home/header-logo.jpg"

export const COMPONENT_DEFAULT_STYLES = {
  text: {
    width: "auto",
    whiteSpace: "pre-wrap",
    overflowWrap: "break-word",
    height: "auto",
    fontSize: "16px",
    color: "#000000",
    lineHeight: 1.5,
    fontWeight: "normal",
    fontFamily: "Arial",
    textIndent: "0px",
    textDecoration: "none",
    letterSpacing: "0px",
    lineSpacing: "0px",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    zIndex:10,
  },
  button: {
    display: "flex",
    width: '120px',
    height: '40px',
    backgroundColor: '#1890ff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    padding: '8px 16px',
    justifyContent: "center",
    alignItems: "center",
    cursor: 'pointer',
    zIndex: 10,
  },
  image: {
    width: '200px',
    height: '150px',
    border: '1px dashed #ddd',
    borderRadius: '4px',
    backgroundImage: `url(${DefaultImage})`,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    zIndex: 10,
  },
  video:{
    width: "auto",
    height: "auto",
    fontSize: "16px",
    color: "#000000",
    lineHeight: 1.5,
    fontWeight: "normal",
    fontFamily: "Arial",
    textIndent: "0px",
    textDecoration: "none",
    letterSpacing: "0px",
    lineSpacing: "0px",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    zIndex:10,
  },
  link:{
    width: "auto",
    height: "auto",
    fontSize: "16px",
    color: "#000000",
    lineHeight: 1.5,
    fontWeight: "normal",
    fontFamily: "Arial",
    textIndent: "0px",
    textDecoration: "none",
    letterSpacing: "0px",
    lineSpacing: "0px",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    zIndex:10,
  },
  nature:{
    width: "auto",
    height: "auto",
    fontSize: "16px",
    color: "#000000",
    lineHeight: 1.5,
    fontWeight: "normal",
    fontFamily: "Arial",
    textIndent: "0px",
    textDecoration: "none",
    letterSpacing: "0px",
    lineSpacing: "0px",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    zIndex:10,
  },
  header:{
    width: "auto",
    height: "auto",
    fontSize: "16px",
    color: "#000000",
    lineHeight: 1.5,
    fontWeight: "normal",
    fontFamily: "Arial",
    textIndent: "0px",
    textDecoration: "none",
    letterSpacing: "0px",
    lineSpacing: "0px",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    zIndex:10,
  },
  chooseCard:{
    width: "auto",
    height: "auto",
    fontSize: "16px",
    color: "#000000",
    lineHeight: 1.5,
    fontWeight: "normal",
    fontFamily: "Arial",
    textIndent: "0px",
    textDecoration: "none",
    letterSpacing: "0px",
    lineSpacing: "0px",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    zIndex:10,
  }
} as const;